### ISSUE TITLE
Add README files to backend and frontend[1pt]

### ISSUE THREAD

**Issue by Amtresu** [PRATAP-KUMAR/book-an-appointment#27]
Add a proper README file to both repos and make sure to use the new microverse readme [template](https://github.com/microverseinc/readme-template), as well as make sure to add links between the two repos between the README files.

**Comment by pratap-panabaka** [comment]
@Amtresu this README does not required PR, so please have a look on both the readme's (for front-end and back-end). Once you are done, please push this task to "done" on this kanban board.

here is the preview


![Image](https://user-images.githubusercontent.com/40719899/212307922-b6d89dd7-b108-4d24-949b-941d76b1045b.gif)



Thank You
